apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: f-partner-catalog
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: f-partner-catalog
    app.kubernetes.io/part-of: partner-catalog
  name: f-partner-catalog
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-springboot-app
      app.kubernetes.io/instance: f-partner-catalog
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-springboot-app
        app.kubernetes.io/instance: f-partner-catalog
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/asaran-tenant/partner-catalog/f-partner-catalog@sha256:41763fd4b4ceb90335b9fedaa018ba4aafb15fd5ad28f095baae5f95bf67a0ea
        name: my-java-springboot
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 180Mi
status: {}
