apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: f-partner-catalog
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/asaran-tenant/partner-catalog/f-partner-catalog@sha256:9ad93d20955278e40eb2d979bacfbaa945cd59b66028c53b4d6b54eaef5b9f88
        name: my-java-springboot
        resources: {}
status: {}
