apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: f-partner-catalog
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: f-partner-catalog
    app.kubernetes.io/part-of: partner-catalog
  name: f-partner-cataloglxuy
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: f-partner-catalog
    weight: null
status: {}
